### ISSUE TITLE
Cannot add arguments from: <class 'probts.model.forecast_module.ProbTSForecastModule'>. You should provide eit her a callable or a subclass of: Trainer,LightningModule,LightningDataModule, or Callback.

### ISSUE THREAD

**Issue by lizhez** [microsoft/ProbTS#25]

**Comment by zhangzw16** [comment]
Hi. It seems there is a problem with adding arguments from the ProbTSForecastModule class. To assist you better, I need more detailed information regarding the context in which this error occurs. Could you please provide the following details:

- A brief description of your use case and the steps leading to this error.
- The code snippet where the error is generated.
- Your config file or run scripts.

**Comment by lizhez** [comment]
![image](https://github.com/user-attachments/assets/535c971c-618c-45d1-a277-f8fe967978ab)
I installed the installation dependency for readme and ran bash reproducte_tsfm_desults. sh, which generated an error as shown in the figure

**Comment by lizhez** [comment]
Hello, my problem has been resolved. I would like to ask how to use probTS for zero-shot testing, can you provide a simple example?

**Comment by zhangzw16** [comment]
For now, the best way to do "zero-shot testing" is through 
``` bash
bash scripts/reproduce_tsfm_results.sh
```

We are also in the process of creating some example code or a Jupyter notebook for this purpose (https://github.com/microsoft/ProbTS/issues/21). Updates will be provided in the related issues, including this one.
