### ISSUE TITLE
Does the repo contain tunable RoPE module in ElasTST? It seems not to be found. Thanks!

### ISSUE THREAD

**Issue by YihengWang828** [microsoft/ProbTS#31]

**Comment by imJiawen** [comment]
Hi @YihengWang828 ,

The tunable RoPE module is available here: https://github.com/microsoft/ProbTS/blob/elastst/probts/model/nn/layers/ElasTSTModule/TRoPE.py

Feel free to reach out if you have any further questions.

**Comment by YihengWang828** [comment]
> 你好[@YihengWang828](https://github.com/YihengWang828)，
> 
> 可调的 RoPE 模块可在此处获取：https://github.com/microsoft/ProbTS/blob/elastst/probts/model/nn/layers/ElasTSTModule/TRoPE.py
> 
> 如果您还有其他问题，请随时与我们联系。



> Hi [@YihengWang828](https://github.com/YihengWang828) ,
> 
> The tunable RoPE module is available here: https://github.com/microsoft/ProbTS/blob/elastst/probts/model/nn/layers/ElasTSTModule/TRoPE.py
> 
> Feel free to reach out if you have any further questions.

Thank you very much for your timely reply!

**Comment by YihengWang828** [comment]
Thank you very much for your timely reply!
